# Generated by Django 5.2.1 on 2025-05-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newa', '0002_category_alter_newa_options_alter_newa_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
